name: Fetch Latest News

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: functions
        run: npm install

      - name: Fetch news
        working-directory: functions
        env:
          NEWSDATA_API_KEY: ${{ secrets.NEWSDATA_API_KEY }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node fetch-news.js